### ISSUE TITLE
The generated HTML has no style in it.

### ISSUE THREAD

**Issue by m4salah** [emad-elsaid/xlog#37]
I really liked your project XLog and inspired me to make my own digital garden as you said, I already tried it but after building the generated html has no style in it, I there is specific step i missed.

**Comment by emad-elsaid** [comment]
Can you provide the steps you followed so I can regenerate the issue on my machine?

**Comment by m4salah** [comment]
I'm Running Windows 11 on my machine.
The steps:
- installed xlog `go install github.com/emad-elsaid/xlog/cmd/xlog@latest`
- `mkdir msalah-site`
- `xlog`
- Then type a basic index file
- `xlog --sitename "Mohamed A. Salah" --build .\msalah_blog_web\`
- The open `index.html` in ` .\msalah_blog_web\` with firefox 

This what looks like.

![Screenshot 2023-09-08 at 22-39-42 Mohamed A  Salah](https://github.com/emad-elsaid/xlog/assets/22938158/ea719b8f-7fe3-4b6c-997e-c268643a55e4)

**Comment by emad-elsaid** [comment]
I see where did it go wrong in this case, I think you opened the file
directly in the browser. but keep in mind that the resources like css/js
are linked in the browser by absolute path

```
   6   │     <link rel="icon" href="/public/logo.png">
   7   │     <link rel="stylesheet" href="/public/style.css">
```
so you have to serve the output directory with a web server and visit
`localhost:port` to load the resources.

the reason this is absolute path because it simplify rendering the page. as
xlog will generate nested pages it's important to refer to the same file.
absolute path makes it easier instead of generating a path relevant to each
generated path `../` `../../../` ..etc.

**Comment by m4salah** [comment]
Okay, I get it now Thanks Emad.
