### ISSUE TITLE
serve and watch and other questions

### ISSUE THREAD

**Issue by juanolon** [emad-elsaid/xlog#52]
Hello,
I just found this gem. The thing is, i already manage my notes separately and i would like to just render the notes. i tried `--build``, but it then creates a new folder for each note file, and polutes my note folder. So i have the following questions:
1) it is possible to build my notes in another folder?
2) does xlog have something like serve & watch
3) coming from hugo, hugo has the flag `--navigateToChanged`, which i find really helpfull when writing notes, would it be feasible to have that too?

thanks!

**Comment by emad-elsaid** [comment]
- it's possible to build the note in another folder `build` command takes a parameter, the path to where to render. only thing is that it won't copy images or any other files so you need to copy relevant files that are not copied by default.
- xlog by default serves the current folder. but caches the rendered files. so it doesn't watch for changes. I like the idea, but I don't have time now to develop it, if you can open a PR that would be beautiful.
- I didn't know about this option `navigateToChanged` in hugo. I believe it can be added as an extension. 
  - the extension can watch for the filesystem changes.
  - and add a script in the page to poll for events
  - when a file changes it pushes the name 
  - the script gets the name of the page and redirect to it or reload current page to show updates

The caching in xlog needs improvement because it only listens on changes when the page is saved not for filesystem changes. I'll try to do that. while developing this cache I noticed asking the system for the last modification time was taking too long so I dropped it. I'll see if there is a filesystem monitor that improves that a bit.

**Comment by emad-elsaid** [comment]
The problem of watching files if it changed and invalidate the cache is interesting for me, I think I'll work on it in the next couple of days

**Comment by juanolon** [comment]
nice :) I started trying an Implementation, but I haven't code golang for years. I just had fswatch set up and listening for changes in the  `Start` method, but then I didn't knew how to update the files. I guess, you will be faster in that manner. I'm glad, you picked interest in the feature :)

**Comment by emad-elsaid** [comment]
the master branch now will watch for the filesystem changes and if the file is written with external editor it'll invalidate the cache for it, so refreshing the browser (manually) will show the latest changes. 

Now we need to do the lats item "navigateToChanged"

**Comment by juanolon** [comment]
wow. that was blazing fast! i'll try this week to make an extension for that :) i'll add a new `PageEvent`, something like `Changed`

**Comment by emad-elsaid** [comment]
Yeah sure, make it work first then we can talk about improving it
